Repository hashicorp/terraform-provider-null, pull requests merged in 2023-08, with the labels that each got.

#249 Adding Terraform 1.5.* to test matrix
  .github/workflows/test.yml
Labels: enhancement, size/XS

#255 cdktf: update documentation
  docs/cdktf/python/data-sources/data_source.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/resource.md
  docs/cdktf/typescript/data-sources/data_source.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/resource.md
Labels: documentation, size/M

#257 cdktf: update documentation
  docs/cdktf/python/data-sources/data_source.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/resource.md
  docs/cdktf/typescript/data-sources/data_source.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/resource.md
Labels: documentation, size/S
