Repository hashicorp/terraform-provider-null, pull requests merged in 2023-03, with the labels that each got.

#190 Update release workflow to use service account PAT
  .github/workflows/release.yml
Labels: size/S

#193 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-161407.yaml
  .github/workflows/test.yml
  README.md
  go.mod
Labels: dependencies, size/XS, go

#196 docs: Prefer brace splat expressions over legacy splat expressions
  docs/data-sources/data_source.md
  docs/resources/resource.md
  examples/data-sources/null_data_source/data-source.tf
  examples/resources/null_resource/resource.tf
Labels: documentation, size/XS

#197 all: Migrate testing to github.com/hashicorp/terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/data_source_test.go
  internal/provider/provider_test.go
  internal/provider/resource_test.go
Labels: dependencies, size/XS, technical-debt

#198 all: Update documentation and null_data_source deprecation for new terraform_data resource
  docs/data-sources/data_source.md
  docs/resources/resource.md
  internal/provider/data_source.go
  internal/provider/resource.go
Labels: documentation, size/XS

#199 all: Add copyright headers and enable compliance checks in CI
  .copywrite.hcl
  .github/workflows/compliance.yml
  internal/planmodifiers/attribute.go
  internal/provider/data_source.go
  internal/provider/data_source_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource.go
  internal/provider/resource_test.go
  main.go
  tools/tools.go
Labels: size/M, legal
