Repository hashicorp/terraform-provider-null, pull requests merged in 2023-11, with the labels that each got.

#275 cdktf: update documentation
  docs/cdktf/python/data-sources/data_source.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/resource.md
  docs/cdktf/typescript/data-sources/data_source.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/resource.md
Labels: documentation, size/XS

#279 Add changelogs for `v3.2.2` release
  .changes/unreleased/NOTES-20230303-161407.yaml
  .changes/unreleased/NOTES-20231120-084555.yaml
Labels: size/XS

#281 .github: Add CI for changie
  .github/workflows/ci-changie.yml
Labels: size/XS

#284 .github: Update workflows to use actions variables
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S

#285 Automatically close associated milestone on release
  .goreleaser.yml
Labels: size/XS
