Repository hashicorp/terraform-provider-null, pull requests merged in 2024-05, with the labels that each got.

#342 docs: Add terraform_data migration guide
  docs/guides/terraform-migration.md
  docs/resources/resource.md
  internal/provider/resource.go
  templates/guides/terraform-migration.md.tmpl
Labels: documentation, size/L

#346 workflows: Delete old issue label remove workflow
  .github/workflows/issue-comment-created.yml
Labels: size/XS

#347 cdktf: update documentation
  docs/cdktf/python/guides/terraform-migration.md
  docs/cdktf/python/resources/resource.md
  docs/cdktf/typescript/guides/terraform-migration.md
  docs/cdktf/typescript/resources/resource.md
Labels: size/XL
